### ISSUE TITLE
Not tracking Fork or Submit functionality here.

### ISSUE THREAD

**Issue by Cfrank482** [learn-co-curriculum/intro-to-capybara#29]

**Comment by maxwellbenton** [comment]
Thank you for spotting this and providing feedback, @Cfrank482.

This issue occurred for multiple students over the past day or so and we believe it was caused by an outage on GitHub (https://www.onmsft.com/news/github-suffers-hours-long-outage-coming-back-online-now). As of now, this lesson is correctly forking and submitting, so I am going to close this issue for now.

If you are still unable to fork this lesson, please re-open this issue. 💙
